POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZvb0JhciIsImlkIjoiNjIxNWEwYWYxMmY0ZTQyMDY2MjdkM2ZmIiwiaWF0IjoxNjQ1NjU3NTI5fQ.4aWw8PJacLqyTYN5WZs_VBHvtEDmkRgnH1OcJOYkOYY

{
  "title": "New authorized blog post",
  "author": "Foo Bar",
  "url": "localhost",
  "userId": "6215a0af12f4e4206627d3ff"
}
